name: Deploy to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}  # можно запускать руками из вкладки Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start ssh-agent and add CI key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Trust VPS host key (known_hosts)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        run: |
          set -e
          ssh -o StrictHostKeyChecking=yes ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} '
            set -e
            echo "==> Pulling latest code"
            cd ${{ secrets.DEPLOY_PATH }}
            # убеждаемся, что есть origin и ветка main
            git fetch origin main || true
            git reset --hard origin/main || {
              echo "[!] origin/main недоступен, пытаюсь настроить remote"
              git remote -v || true
              exit 1
            }

            echo "==> Building and restarting containers"
            cd infra
            docker compose build site
            docker compose up -d

            echo "==> Versions / status"
            docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
          '
